### ISSUE TITLE
any screenshots / output?

### ISSUE THREAD

**Issue by johndpope** [stephanj/basketballVideoAnalysis#1]

**Comment by stephanj** [comment]
Output from the Mask R-CNN application below

![result](https://user-images.githubusercontent.com/179457/71007780-da496a00-20e7-11ea-8f7e-b45c06d2786e.jpg)

And also video version @ https://www.youtube.com/watch?v=yEqGTSd5DQU 

These were also highlighted on the wiki page @ https://github.com/stephanj/basketballVideoAnalysis/wiki 

Work in progress : Court detection, player identification and homography court mapping.

**Comment by johndpope** [comment]
great!
